-- 1. Create Tables (If they don't exist)
CREATE TABLE IF NOT EXISTS public.shops (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    owner_id UUID REFERENCES auth.users(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    generic_name TEXT,
    batch_number TEXT,
    expiry_date DATE,
    quantity INTEGER DEFAULT 0,
    mrp NUMERIC,
    min_stock_level INTEGER DEFAULT 10,
    shop_id UUID REFERENCES public.shops(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT,
    mobile_number TEXT,
    total_amount NUMERIC,
    status TEXT DEFAULT 'pending', -- pending, completed, cancelled
    shop_id UUID REFERENCES public.shops(id),
    items JSONB, -- Storing items as JSON for simplicity in SaaS v1
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    total_visits INTEGER DEFAULT 0,
    shop_id UUID REFERENCES public.shops(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS
ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
-- SHOPS
CREATE POLICY "Users can view own shop" ON shops
    FOR SELECT TO authenticated
    USING (auth.uid() = owner_id);

CREATE POLICY "Users can insert own shop" ON shops
    FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = owner_id);

-- MEDICINES
CREATE POLICY "Users can view own shop medicines" ON medicines
    FOR ALL TO authenticated
    USING (shop_id IN (SELECT id FROM shops WHERE owner_id = auth.uid()));

-- ORDERS
CREATE POLICY "Users can view own shop orders" ON orders
    FOR ALL TO authenticated
    USING (shop_id IN (SELECT id FROM shops WHERE owner_id = auth.uid()));

-- CUSTOMERS
CREATE POLICY "Users can view own shop customers" ON customers
    FOR ALL TO authenticated
    USING (shop_id IN (SELECT id FROM shops WHERE owner_id = auth.uid()));

-- 4. Initial Shop Creation Trigger (Optional, simplifies onboarding)
-- When a new user signs up, automatically create a shop for them? 
-- For now, we will handle this in the frontend or let the user create it manually.
