-- 1. Create Tables (If they don't exist)
CREATE TABLE IF NOT EXISTS public.shops (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    owner_id UUID REFERENCES auth.users(id) NOT NULL,
    gstin TEXT,
    dl_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    generic_name TEXT,
    batch_number TEXT,
    expiry_date DATE,
    quantity INTEGER DEFAULT 0,
    mrp NUMERIC,
    min_stock_level INTEGER DEFAULT 10,
    shop_id UUID REFERENCES public.shops(id),
    hsn_code TEXT,
    sgst_rate NUMERIC DEFAULT 0,
    cgst_rate NUMERIC DEFAULT 0,
    igst_rate NUMERIC DEFAULT 0,
    schedule_h1 BOOLEAN DEFAULT FALSE,
    salt_composition TEXT,
    manufacturer TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT,
    mobile_number TEXT,
    total_amount NUMERIC,
    tax_total NUMERIC DEFAULT 0,
    invoice_number TEXT,
    status TEXT DEFAULT 'pending', -- pending, completed, cancelled
    shop_id UUID REFERENCES public.shops(id),
    items JSONB, -- Storing items as JSON for simplicity in SaaS v1
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    total_visits INTEGER DEFAULT 0,
    shop_id UUID REFERENCES public.shops(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- B2B & Distributors
CREATE TABLE IF NOT EXISTS public.distributors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_info TEXT,
    catalog_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.catalogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distributor_id BIGINT REFERENCES public.distributors(id),
    drug_name TEXT NOT NULL,
    brand TEXT,
    price NUMERIC,
    min_order_qty INTEGER DEFAULT 1,
    in_stock BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.b2b_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distributor_id BIGINT REFERENCES public.distributors(id),
    shop_id UUID REFERENCES public.shops(id),
    items JSONB,
    status TEXT DEFAULT 'placed',
    total_amount NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS
ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies

-- PROFILES (Users can view their own profile)
CREATE POLICY "Users can view own profile" ON profiles
    FOR SELECT TO authenticated
    USING (user_id = auth.uid());

CREATE POLICY "Users can update own profile" ON profiles
    FOR UPDATE TO authenticated
    USING (user_id = auth.uid());

-- SHOPS
-- Allow read access if you are the owner OR if you are a staff member linked to this shop
CREATE POLICY "Team access shop" ON shops
    FOR SELECT TO authenticated
    USING (
        id IN (
            SELECT shop_id FROM profiles WHERE user_id = auth.uid()
        )
    );

CREATE POLICY "Owner update shop" ON shops
    FOR UPDATE TO authenticated
    USING (owner_id = auth.uid());

-- MEDICINES
CREATE POLICY "Team access medicines" ON medicines
    FOR ALL TO authenticated
    USING (
        shop_id IN (
            SELECT shop_id FROM profiles WHERE user_id = auth.uid()
        )
    );

-- ORDERS
CREATE POLICY "Team access orders" ON orders
    FOR ALL TO authenticated
    USING (
        shop_id IN (
            SELECT shop_id FROM profiles WHERE user_id = auth.uid()
        )
    );

-- CUSTOMERS
CREATE POLICY "Team access customers" ON customers
    FOR ALL TO authenticated
    USING (
        shop_id IN (
            SELECT shop_id FROM profiles WHERE user_id = auth.uid()
        )
    );

-- 4. Database Triggers for Auto-Onboarding
-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    new_shop_id UUID;
BEGIN
    -- 1. Create a new Profile for the user
    -- We assume initially they have no shop, unless they created one.
    -- But for simplicity, every new signup CREATES a shop by default in this MVP,
    -- UNLESS we implement an invite flow later.
    
    -- Insert Shop
    INSERT INTO public.shops (name, owner_id)
    VALUES (
        COALESCE(new.raw_user_meta_data->>'shop_name', 'My Medical Shop'),
        new.id
    )
    RETURNING id INTO new_shop_id;

    -- Insert Profile linked to that shop
    INSERT INTO public.profiles (user_id, full_name, role, shop_id)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'full_name', 'New User'),
        'admin', -- Default to admin for creator
        new_shop_id
    );

    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function on Auth User Created
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. Storage Buckets & Policies
-- Note: You must create a public bucket named 'clinical-uploads' in your Supabase Storage settings first.

-- Policy: Allow authenticated uploads
create policy "Allow authenticated uploads"
on storage.objects for insert
to authenticated
with check ( bucket_id = 'clinical-uploads' );

-- Policy: Allow users to view their own uploaded files
create policy "Allow users to view own files"
on storage.objects for select
to authenticated
using ( bucket_id = 'clinical-uploads' AND auth.uid()::text = (storage.foldername(name))[1] );


