
export interface WhatsAppOrder {
    invoice_number?: string;
    customer_name: string;
    shop_name?: string;
    created_at: string;
    total_amount: number | null;
    status: string;
    items: { name: string; qty?: number; price: number }[];
}

export interface WhatsAppPrescription {
    doctor_name: string;
    customer_name: string;
    visit_date: string;
    medicines: { name: string; dosage: string }[];
}

export interface WhatsAppReport {
    summary: string;
    diseasePossibility: string[];
    diet: string[];
    nextSteps: string[];
}

export const whatsappService = {
    /**
     * Helper to format phone number to international format (91 prefix)
     */
    formatPhone(phone: string | null): string {
        if (!phone) return "";
        const clean = phone.replace(/\D/g, '');
        if (clean.length === 10) return `91${clean}`;
        return clean;
    },

    /**
     * Generate Invoice Message
     */
    generateInvoiceLink(phone: string | null, order: WhatsAppOrder): string {
        const itemsList = order.items.map((item, idx) =>
            `${idx + 1}. ${item.name} x${item.qty || 1} = ₹${item.price * (item.qty || 1)}`
        ).join('\n');

        const message = `🧾 *INVOICE #${order.invoice_number || 'NA'}*\n` +
            `🏪 *${order.shop_name || 'Medix Pharmacy & Diagnostics'}*\n` +
            `📍 Date: ${new Date(order.created_at).toLocaleDateString()}\n` +
            `--------------------------------\n` +
            itemsList +
            `\n--------------------------------\n` +
            `💰 *GRAND TOTAL: ₹${order.total_amount}*\n` +
            `✅ Status: ${order.status.toUpperCase()}\n` +
            `--------------------------------\n` +
            `Thank you for your trust! 🙏\n` +
            `_Powered by MedixAI_`;

        return `https://wa.me/${this.formatPhone(phone)}?text=${encodeURIComponent(message)}`;
    },

    /**
     * Generate Prescription Message
     */
    generatePrescriptionLink(phone: string | null, prescription: WhatsAppPrescription): string {
        const medsList = prescription.medicines.map((m, idx) =>
            `${idx + 1}. *${m.name}*\n   Dosage: ${m.dosage}`
        ).join('\n');

        const message = `👨‍⚕️ *DIGITAL PRESCRIPTION*\n` +
            `🏥 *Medix Pharmacy & Diagnostics*\n` +
            `Date: ${new Date(prescription.visit_date).toLocaleDateString()}\n\n` +
            `Patient: ${prescription.customer_name}\n` +
            `Doctor: ${prescription.doctor_name}\n` +
            `--------------------------------\n` +
            `💊 *MEDICINES:*\n` +
            medsList +
            `\n--------------------------------\n` +
            `\n_Get these medicines delivered via Medix App!_`;

        return `https://wa.me/${this.formatPhone(phone)}?text=${encodeURIComponent(message)}`;
    },

    /**
     * Generate Lab Report Summary Message
     */
    generateReportLink(phone: string | null, report: WhatsAppReport): string {
        const message = `*🏥 MedixAI Report Summary*\n\n` +
            `*Summary:* ${report.summary}\n\n` +
            `*🚨 Possibility:* ${report.diseasePossibility.join(", ")}\n\n` +
            `*🥗 Recommended Diet:* ${report.diet.join(", ")}\n\n` +
            `*👨‍⚕️ Next Steps:* ${report.nextSteps.join(", ")}\n\n` +
            `_Generated by MedixAI_`;

        return `https://wa.me/${this.formatPhone(phone)}?text=${encodeURIComponent(message)}`;
    },
    /**
     * Generate Return Note Message
     */
    generateReturnMessage(phone: string | null, details: { shop_name?: string, supplier_name: string, item_count: number }): string {
        const message = `👋 Hi ${details.supplier_name},\n\n` +
            `Please find attached the *Purchase Return Note* from ${details.shop_name || 'us'}.\n` +
            `Total Items: ${details.item_count}\n\n` +
            `Kindly process the credit note.\n` +
            `_Sent via PharmaAssist_`;

        return `https://wa.me/${this.formatPhone(phone) || ''}?text=${encodeURIComponent(message)}`;
    }
};
