-- 1. Create Distributors Table (if missing) based on usage in Marketplace.tsx
CREATE TABLE IF NOT EXISTS public.distributors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    contact_phone TEXT,
    contact_email TEXT,
    rating NUMERIC DEFAULT 5.0,
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 1b. Fix Schema if table already existed without these columns
ALTER TABLE public.distributors ADD COLUMN IF NOT EXISTS contact_phone TEXT;
ALTER TABLE public.distributors ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE public.distributors ADD COLUMN IF NOT EXISTS rating NUMERIC DEFAULT 5.0;
ALTER TABLE public.distributors ADD COLUMN IF NOT EXISTS address TEXT;

-- 2. Create Catalogs Table (if missing) based on usage in Marketplace.tsx
CREATE TABLE IF NOT EXISTS public.catalogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distributor_id BIGINT REFERENCES public.distributors(id) ON DELETE CASCADE,
    drug_name TEXT NOT NULL,
    brand TEXT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    min_order_qty INTEGER DEFAULT 10,
    in_stock BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. Enable RLS for these new tables (Basic)
ALTER TABLE public.distributors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalogs ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'distributors' AND policyname = 'Public read access') THEN
        CREATE POLICY "Public read access" ON public.distributors FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'catalogs' AND policyname = 'Public read access') THEN
        CREATE POLICY "Public read access" ON public.catalogs FOR SELECT USING (true);
    END IF;
END $$;


-- 4. Seed Distributors (Placeholder Data)
INSERT INTO public.distributors (name, contact_phone, rating, address)
VALUES 
    ('Apollo Wholesalers', '+91-9876543210', 4.8, 'Andheri East, Mumbai'),
    ('MediConnect Hub', '+91-1122334455', 4.5, 'Connaught Place, Delhi'),
    ('Global Pharma Supply', '+91-5566778899', 4.2, 'Tech City, Bangalore')
ON CONFLICT (name) DO NOTHING;

-- 5. Seed Catalogs (Linked to Distributors)
-- We use subqueries to get IDs dynamically
INSERT INTO public.catalogs (distributor_id, drug_name, brand, price, min_order_qty, in_stock)
SELECT id, 'Paracetamol 500mg', 'Dolo-650', 14.50, 50, true FROM public.distributors WHERE name = 'Apollo Wholesalers'
UNION ALL
SELECT id, 'Amoxicillin 500mg', 'Mox-500', 45.00, 20, true FROM public.distributors WHERE name = 'Apollo Wholesalers'
UNION ALL
SELECT id, 'Azithromycin 500mg', 'Azithral-500', 110.00, 10, true FROM public.distributors WHERE name = 'Apollo Wholesalers'
UNION ALL
SELECT id, 'Cetirizine 10mg', 'Cetzine', 18.00, 100, true FROM public.distributors WHERE name = 'MediConnect Hub'
UNION ALL
SELECT id, 'Pantoprazole 40mg', 'Pan-40', 85.00, 30, true FROM public.distributors WHERE name = 'MediConnect Hub'
UNION ALL
SELECT id, 'Metformin 500mg', 'Glycomet-500SR', 22.50, 40, true FROM public.distributors WHERE name = 'Global Pharma Supply'
UNION ALL
SELECT id, 'Atorvastatin 10mg', 'Atorva-10', 75.00, 25, true FROM public.distributors WHERE name = 'Global Pharma Supply';


-- 6. Seed Inventory (Lite Mode - Important Medicines)
-- Attaches to the first shop found in the database.
INSERT INTO public.inventory (
    shop_id, 
    medicine_name, 
    batch_number, 
    expiry_date, 
    quantity, 
    unit_price, 
    mrp, 
    manufacturer, 
    category
)
SELECT 
    id as shop_id,
    medicine_name,
    batch_number,
    expiry_date,
    quantity,
    unit_price,
    mrp,
    manufacturer,
    category
FROM public.shops, (
    VALUES 
        ('Dolo 650', 'BATCH001', CURRENT_DATE + INTERVAL '365 days', 250, 1.50, 2.00, 'Micro Labs', 'Tablet'),
        ('Saridon', 'BATCH002', CURRENT_DATE + INTERVAL '180 days', 100, 3.50, 5.00, 'Piramal', 'Tablet'),
        ('Augmentin 625 Duo', 'BATCH003', CURRENT_DATE + INTERVAL '730 days', 50, 45.00, 60.00, 'GSK', 'Tablet'),
        ('Becosules', 'BATCH004', CURRENT_DATE + INTERVAL '500 days', 80, 2.50, 4.00, 'Pfizer', 'Capsule'),
        ('Ascoril D Plus', 'BATCH005', CURRENT_DATE + INTERVAL '300 days', 30, 85.00, 110.00, 'Glenmark', 'Syrup')
) AS data(medicine_name, batch_number, expiry_date, quantity, unit_price, mrp, manufacturer, category)
LIMIT 1;
