// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values to prevent crash during initial load if env vars are missing
const FALLBACK_URL = "https://placeholder-project.supabase.co";
const FALLBACK_KEY = "placeholder-key";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || import.meta.env.SUPABASE_URL || FALLBACK_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.SUPABASE_PUBLISHABLE_KEY || FALLBACK_KEY;

if (SUPABASE_URL === FALLBACK_URL) {
  console.warn("⚠️ Supabase URL is missing! Using fallback. Checked VITE_SUPABASE_URL and SUPABASE_URL.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  db: {
    schema: 'public',
  },
  global: {
    headers: { 'x-application-name': 'medix-ai-dashboard' },
  },
});

// Connectivity Check Helper
export const checkConnection = async () => {
  try {
    const { error } = await supabase.from('shops').select('id').limit(1).maybeSingle();
    if (error) throw error;
    return true;
  } catch (e) {
    console.warn("Supabase Connectivity Check Failed", e);
    return false;
  }
};